# Generated by Django 4.2.6 on 2024-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_tracking', '0003_alter_purchaseorder_acknowledgment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
